kind: pipeline
type: docker
name: default

services:
  selenium:
    image: selenium/standalone-chrome

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - python -V
