kind: pipeline
type: docker
name: default

services:
  selenium:
    image: selenium/hub
  chrome:
  commands:
  - sleep 20
    image: selenium/node-chrome:2.48.2
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"

pipeline:
  build:
    image: python
    commands:
      - sleep 20
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - python scripts.py
