kind: pipeline
type: docker
name: default

# services:
# - name: chrome
#   image: selenium/standalone-chrome:4.1.4-20220427

# steps:
# - name: test
#   image: python
#   commands:
#   - pip install -r requirements.txt
#   - pytest
pipeline:
  build:
    image: python
    commands:
      - sleep 30
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - python scripts.py
#       - pytest

services:
  selenium:
    image: selenium/standalone-chrome
