kind: pipeline
type: docker
name: default

services:
  - name: selenium
    image: selenium/hub

  - name: chrome
    image: selenium/node-chrome
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
      DISPLAY: ":99.0"


steps:
  name: test
  image: python
  commands:
    - sleep 20
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - python scripts.py
