kind: pipeline
type: docker
name: default

services:
- name: chrome
  image: browserless/chrome:latest
  ports:
  - 3000

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
