kind: pipeline
type: docker
name: default

services:
- name: chrome
  image: selenium/standalone-chrome:4.1.4-20220427

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
