kind: pipeline
type: docker
name: default

services:
- name: chrome
  image: chromedp/headless-shell:latest
  ports:
  - 9222

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
