# kind: pipeline
# type: docker
# name: default

# steps:
# - name: test
#   image: python
#   commands:
#   - pip install -r requirements.txt
#   - pytest

# services:
#   selenium:
#     image: selenium/standalone-chrome
pipeline:
  test:
    image: python
      commands:
      - pip install -r requirements.txt
      - pytest

services:
  selenium:
    image: selenium/standalone-chrome
