kind: pipeline
type: docker
name: default

services:
- name: chrome
  image: chromedp/headless-shell
  commands:
  - docker run -d -p 9222:9222 --rm --name headless-shell chromedp/headless-shell
  - docker run -d -p 9222:9222 --rm --name headless-shell --shm-size 2G chromedp/headless-shell

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
