kind: pipeline
type: docker
name: default

services:
  selenium:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    environment:
      SE_EVENT_BUS_HOST: selenium
      SE_EVENT_BUS_PUBLISH_PORT: 4444
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: ":99.0"


pipeline:
  build:
    image: python
    commands:
      - sleep 20
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - python scripts.py
