kind: pipeline
type: docker
name: default

services:
- name: selenium
  image: selenium/standalone-chrome
  commands:
  - docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.1.4-20220427

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
