kind: pipeline
type: docker
name: default

services:
- name: chrome
  image: docker
  commands:
  - addgroup --system docker
  - adduser $USER docker
  - newgrp docker
  - reboot
  - docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.1.4-20220427

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
